apiVersion: v1
kind: Pod
metadata:
  name: denistart
  labels:
    type: web
spec:
  containers:
  - name: denistartcontainer
    image: denimallel/denistart
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
